class WaitElements:

    # RSA Health Wait Elements

    PinCodeTextBox = "//input[@placeholder='Where do you stay']"
    SelfCheckBox = "//*[text()='Self']/following-sibling::mat-checkbox"
    SelfAgeTextBox = "//input[@placeholder='Enter Age']"
    ShareQuotesButton = "//*[contains(text(),'Share Quotes')]"
    SelectAllQuotesCheckBox = "//input[@id='selectAll']"
    NameTextBox = "//input[@placeholder='Please enter your name']"
    CloseButton = "//img[@type='button']"
    RSAPlanSelectButton = "//*[@class='outer outer-min-height']//*[contains(@src,'royal_sundaram')]//ancestor::div[@style='flex-direction: row; box-sizing: border-box; display: flex;']//div//button"
    NextButton = "//p[@class='ng-star-inserted']"
    FirstNameTextBox = "//input[@formcontrolname='first_name']"
    SelectOccupationOption = "//span[contains(text(),'Salaried')]"
    MaritalStatusOption = "//span[text()=' Single ' and @class='mat-option-text']"
    QualificationOption = "//span[text()=' Graduate ' and @class='mat-option-text']"
    TPANameOption = "//span[text()=' Medi Assist Insurance (TPA) Pvt Ltd ' and @class='mat-option-text']"
    SelfFirstNameTextBox = "//input[@formcontrolname='first_name']"
    NomRelationOption = "//span[text()=' Wife ' and @class='mat-option-text']"
    QuestPageButton = "//p[@class='ng-star-inserted']"
    NameValidationText = "//div[@class='col-12 col-md-4']/h5"
    ShareButton = "//button[contains(text(),'Share')]"

    # RSA Two Wheeler Wait Elements

    RSATWOption = "//*[contains(text(),'2 Wheeler Insurance')]"
    RSATWVhclInfoOption = "//button[@class='buyBtn pointer']"
    RSATWSelectBrandButton = "//img[@src='https://dssrylrxc4fuc.cloudfront.net/attachments/files/000/000/027/original/download.png?1633038024']"
    RSATWInputBrndTxtBox = "input[name='brandTxt']"
    RSATWInputRTOTextBox = "//input[@id='mat-input-3']"
    RSATWPrevPolStsTextBox = "//input[@placeholder='dd/ mm/ yyyy']"
    RSATWShareQuotesButton = "//span[contains(text(),'SHARE QUOTE')]"
    RSATWShareQuotesNameTxtBox = "//div[contains(@class,'desktop_screen_only')]//input[@name='name']"
    RSATWRSAComButton = "(//img[not (@class) and contains(@src,'royal_sundaram')]//ancestor::div[@class='ng-star-inserted']//button[@class='btn-m-orange'])[2]"
    RSATWProceedButton = "//div[@class='col-xs-4 col-md-4 col-lg-4 right-section']//button[contains(text(),'PROCEED')]"
    RSATWVhclOwnrshpChngedOption = "(//span[@class='mat-option-text'])[2]"
    RSATWFinancedOption = "//span[@class='mat-option-text' and contains(text(),'Yes')]"
    RSATWFinancerTypeOption = "//span[@class='mat-option-text' and contains(text(),'Hire')]"
    RSATWPUCOption = "RSAtwpucoption_XPATH"
    RSATWPrevInsComOption = "//span[@class='mat-option-text' and contains(text(),'United India Insurance')]"
    RSATWPrevPolTypeOption = "//span[@class='mat-option-text' and contains(text(),'Comprehensive')]"
    RSATWNomineeRltnOption = "//span[@class='mat-option-text' and contains(text(),'Spouse')]"
    RSATWCPACoverOption = "//span[@class='mat-option-text' and contains(text(),'Driving')]"
    RSATWPrefixOption = "(//span[@class='mat-option-text' and contains(text(),'Mr')])[1]"
    RSATWGenderOption = "//span[@class='mat-option-text' and contains(text(),'Male')]"
    RSATWProceedToReviewPageButton = "(//button[contains(text(),' PROCEED ')])[2]"
    RSATWVerifyRegNoText = "(//div[@class='col-xs-6 col-md-6 question-ans bold'])[2]"
    RSATWFinalShareButton = "//button[@type='submit']"

    # RSA Four Wheeler Wait Elements

    RSAFWOption = "//*[contains(text(),'2 Wheeler Insurance')]"
    RSAFWVhclInfoOption = "//button[@class='buyBtn pointer']"
    RSAFWSelectBrandButton = "//img[@src='https://dssrylrxc4fuc.cloudfront.net/attachments/files/000/000/027/original/download.png?1633038024']"
    RSAFWInputBrndTxtBox = "input[name='brandTxt']"
    RSAFWInputRTOTextBox = "//input[@id='mat-input-3']"
    RSAFWPrevPolStsTextBox = "//input[@placeholder='dd/ mm/ yyyy']"
    RSAFWShareQuotesButton = "//span[contains(text(),'SHARE QUOTE')]"
    RSAFWShareQuotesNameTxtBox = "//div[contains(@class,'desktop_screen_only')]//input[@name='name']"
    RSAFWRSAComButton = "(//img[not (@class) and contains(@src,'royal_sundaram')]//ancestor::div[@class='ng-star-inserted']//button[@class='btn-m-orange'])[2]"
    RSAFWProceedButton = "//div[@class='col-xs-4 col-md-4 col-lg-4 right-section']//button[contains(text(),'PROCEED')]"
    RSAFWVhclOwnrshpChngedOption = "(//span[@class='mat-option-text'])[2]"
    RSAFWFinancedOption = "//span[@class='mat-option-text' and contains(text(),'Yes')]"
    RSAFWFinancerTypeOption = "//span[@class='mat-option-text' and contains(text(),'Hire')]"
    RSAFWPUCOption = "RSAtwpucoption_XPATH"
    RSAFWPrevInsComOption = "//span[@class='mat-option-text' and contains(text(),'United India Insurance')]"
    RSAFWPrevPolTypeOption = "//span[@class='mat-option-text' and contains(text(),'Comprehensive')]"
    RSAFWNomineeRltnOption = "//span[@class='mat-option-text' and contains(text(),'Spouse')]"
    RSAFWCPACoverOption = "//span[@class='mat-option-text' and contains(text(),'Driving')]"
    RSAFWPrefixOption = "(//span[@class='mat-option-text' and contains(text(),'Mr')])[1]"
    RSAFWGenderOption = "//span[@class='mat-option-text' and contains(text(),'Male')]"
    RSAFWProceedToReviewPageButton = "(//button[contains(text(),' PROCEED ')])[2]"
    RSAFWVerifyRegNoText = "(//div[@class='col-xs-6 col-md-6 question-ans bold'])[2]"
    RSAFWFinalShareButton = "//button[@type='submit']"
